# Server Configuration

# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=money-manager

# Application Name
spring.application.name=money-manager-backend
#server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
# 86400000 ms = 24 hours
server.port=8081
# CORS Configuration
cors.allowed-origins=http://localhost:3000

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.moneymanager=DEBUG

# ?? Gmail SMTP ????????????????????????????????????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=medical.iot.alert@gmail.com
spring.mail.password=lqkuqjmttndaqdvt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000