# Server Configuration
server.port=5000

# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=money-manager

# Application Name
spring.application.name=money-manager-backend

# CORS Configuration
cors.allowed-origins=http://localhost:3000

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.moneymanager=DEBUG
